# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 365d8763039db26756210d5c33d2f68222c1dfe3206f8a59b03caacf313e4b4b8e364f766381658cbb0c4fec803b13037cc6e9c614132e5ba350aba7f4e4365d

test:
  secret_key_base: 763512ff476bccff265e41061614cf35d1345b4fb07fdeab54c23179e2439269608c155575c3856e4dce4022525a91e664d109568ac3642ff068e23fb22b3f0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
